# This file was generated by GoReleaser. DO NOT EDIT.
cask "swg" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "afbf25d624fe0a0ac8cbbade00f91c3c56b78ba13b3122f0e8a092eba1d7abed"
      url "https://github.com/madsboddum/swg-cli/releases/download/v#{version}/swg-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "cd4fb9ca895fd68501c884b11f54b9058336af903d5c8232c84b84d5b37dca9e"
      url "https://github.com/madsboddum/swg-cli/releases/download/v#{version}/swg-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f5c4becd925d24ddc3db59f5f117edb445888bedd5efe8471f031c7c1984b011"
      url "https://github.com/madsboddum/swg-cli/releases/download/v#{version}/swg-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "eccdd3584a037c4ea5e5a3561196a133cdb4af89eb323a7cfed1aec326f2c8e1"
      url "https://github.com/madsboddum/swg-cli/releases/download/v#{version}/swg-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "swg"
  desc "Command line tool for the file formats found in Star Wars Galaxies"
  homepage "https://github.com/madsboddum/swg-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "swg"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/swg"]
    end
  end

  # No zap stanza required
end
