# This file was generated by GoReleaser. DO NOT EDIT.
cask "swg" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "1519eec2a6b19f744a1fca2eabb4c55b9c8c075a77285bcfab2027058c1f3306"
      url "https://github.com/madsboddum/swg-cli/releases/download/v#{version}/swg-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "61ab85dd190921dd3bfdb3bd32798f28e9db22b833375fd6dba2a5ef1a19d5f8"
      url "https://github.com/madsboddum/swg-cli/releases/download/v#{version}/swg-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6b294e60d582e2e3bcef9ebbdcfe4bbec65afde1fe4f5d26c3e621f212c7523d"
      url "https://github.com/madsboddum/swg-cli/releases/download/v#{version}/swg-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1d8edef539e5720e39fde405973ec5b58b424f198128652302e149f6e1dd88dc"
      url "https://github.com/madsboddum/swg-cli/releases/download/v#{version}/swg-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "swg"
  desc "Command line tool for the file formats found in Star Wars Galaxies"
  homepage "https://github.com/madsboddum/swg-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "swg"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/swg"]
    end
  end

  # No zap stanza required
end
