# This file was generated by GoReleaser. DO NOT EDIT.
cask "swg" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "1874e28c08c2ee8d8b5f18d462f2264b2efaabe4d55b10c924d9d9e25d13acf0"
      url "https://github.com/madsboddum/swg-cli/releases/download/v#{version}/swg-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "85d63604cfa12829566eb142df088129fdb3db7357d4dd7fd4939baf704c8b75"
      url "https://github.com/madsboddum/swg-cli/releases/download/v#{version}/swg-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "eff501fa5171d091e9c536b56341cac4a788a939531ab6f42bd6bb8c6ae43c92"
      url "https://github.com/madsboddum/swg-cli/releases/download/v#{version}/swg-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d48240486f507524dcfc07465b9ed035f55f62aba7eef4f64d4740d4e7f0b53d"
      url "https://github.com/madsboddum/swg-cli/releases/download/v#{version}/swg-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "swg"
  desc "Command line tool for the file formats found in Star Wars Galaxies"
  homepage "https://github.com/madsboddum/swg-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "swg"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/swg"]
    end
  end

  # No zap stanza required
end
